name: Setup
description: Setup and install dependencies

inputs:
  install_flags:
    description: pnpm install flags
    default: ""

runs:
  using: composite
  steps:
    - run: corepack enable pnpm
      shell: bash

    - uses: actions/setup-node@v5
      with:
        node-version-file: .node-version

    - run: pnpm install --frozen-lockfile ${{ inputs.install_flags }}
      shell: bash
