/**
 * Generated by @openapi-codegen
 *
 * @version 1.85.0
 */
import type * as Schemas from "./native-api-schemas";

export type NotFound = Schemas.ErrorResponse;

export type ValidationErrors = Schemas.ErrorResponse;

export type UnauthorizedAccess = Schemas.ErrorResponse;

export type UnauthorizedApplication = Schemas.ErrorResponse;

export type InternalError = Schemas.ErrorResponse;

export type NoItemsLeftOrLicensingSerialsExportError = Schemas.ErrorResponse;
