name: E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    name: E2E
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup

      - run: pnpm test:e2e --cache-dir=${{ steps.setup.outputs.turbo_cache_dir }}
